.TH DUET 1 "DOCUMENTATION"
.hy
.SH NAME
duet \- minimalist dual pane terminal file manager

.SH SYNOPSIS
.B duet

.SH DESCRIPTION
duet is a dual pane terminal file manager.
.PP
Left pane navigates filesystem. Right pane shows live preview: directories (contents),
text files (first screenful), binaries (sanitized dump).

.SH QUICK REFERENCE
.RS 4
.TP 12
navigate
.BR hjkl " or arrows"
.TP 12
parent dir
.BR h ", <"
.TP 12
enter/open  
.BR l ", >, Enter"
.TP 12
top/bottom  
.BR g ", G"
.TP 12
hidden     
.B "."
.TP 12
home       
.B "~"
.TP 12
fuzzy find 
.BR Tab
.TP 12
shell      
.B "!"
.TP 12
quit       
.BR q ", Ctrl-C"
.RE

.SH BUILD
.B gcc -o duet duet.c
.PP
or
.B make

.SH INSTALL
.B make install

.SH AUTHOR
Ivan Gaydardzhiev

.SH COPYRIGHT
Copyright \(co 2026 Ivan Gaydardzhiev
.br
GPL-3.0-only
